### ISSUE TITLE
2.0.1-2 - domReady.js not found in WebJar

### ISSUE THREAD

**Issue by Jsmmmm** [webjars/requirejs-domready#4]
WebJar Not Found org.webjars : requirejs-domready : 2.0.1-2 - domReady.js not found in WebJar

https://cdn.jsdelivr.net/webjars/requirejs-domready/2.0.1-2/domReady.js

**Comment by jamesward** [comment]
There was an issue with how this WebJar was packaged.  I'm releasing `2.0.1-3` now which should fix it.
